# The default way of registering routes in your application is via config files.
# The root-level keys ("first.route") are route names.

first.route:
  method: GET
  path: '/'
  controller: [MyApplication\Web\ExampleController, exampleAction]

second.route:
  method: GET
  path: '/bar/{foo}'
  controller: [MyApplication\Web\ExampleController, otherAction]
